# Dev profile
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:devdb
  security:
    user:
      name: admin
      password: admin
server:
  port: 8081
# QA profile
---
spring:
  config:
    activate:
      on-profile: qa
  datasource:
    url: jdbc:h2:mem:qadb
  security:
    user:
      name: admin
      password: admin
server:
  port: 8082